[package]
name = "tron_address_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = { version = "0.24", features = ["rand-std"] }
rand = "0.8"
sha3 = "0.10"
sha2 = "0.10"
bs58 = "0.4"
dotenv = "0.15"
hex = "0.4"